name: Carolyn Scanlon
favicon: null
layout_spectrum: 0.75818
typography_spectrum: 0.12512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#797471'
    - '#c0bd9e'
    - '#131315'
    - '#e25b62'
    - '#703523'
  brandStrength: 0.5
  lightness: 0.7007865707855672
  saturation: 0.375
  rhythmicContrast: 0.8482045461423695
purpose: []
